spring:
  datasource:
    url: jdbc:h2:mem:rest_dev_week
    username: dev123
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

dependencies:
  groupId: org.springdoc
  artifactId: springdoc-openapi-starter-webmvc-ui
  version: 2.5.0
